a = input('Digite qualquer coisa:')
print('O tipo primitivo deste valor é:' , type(a))
print('Só tem espaços?' , a.isspace())
print('É um número?' , a.isnumeric())
print('É alfabético?' , a.isalpha())
print('É alfanumérico?' , a.isalnum())
print('Esta em maiúsculo?' , a.isupper())
print('Esta em minusculo?' , a.islower())
print('Esta capitalizada?' , a.istitle())